title: Volving
description: My Personal Blog
author: Volving
logo: "static/img/avatar.png"
github: https://github.com/volving
about: Freelance developer

baseurl: ""
url: "http://v.vno.io/"

# disqus_shortname:
# google_analytics: UA-72862926-1

share:
  # twitter_username: \#
  # fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
